on:
  push:
    branches: ["**"]

jobs:
  require_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          pipx run ./x.py
        env:
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
