on:
  push:
    branches: ["**"]

jobs:
  require_review:
    runs-on: ubuntu-latest
    steps:
      - run:
          pipx run x.py
        env:
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
